version: '3.9'
services:
  web:
    image: 'ghcr.io/postalserver/postal:3.3.4'
    command: 'postal web-server'
    volumes:
      - '/opt/postal/config:/config'
    restart: unless-stopped
  smtp:
    image: 'ghcr.io/postalserver/postal:3.3.4'
    command: 'postal smtp-server'
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - '/opt/postal/config:/config'
    restart: unless-stopped
  worker:
    image: 'ghcr.io/postalserver/postal:3.3.4'
    command: 'postal worker'
    volumes:
      - '/opt/postal/config:/config'
    restart: unless-stopped
